spring:
  profiles:
    active: docker
---
spring:
  profiles:
    name: cloud
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/kbastani/spring-boot-microservice-config
        health:
          repositories:
            movie:
              label: master
              profiles: cloud
            rating:
              label: master
              profiles: cloud
server:
  port: 8443
  ssl:
    key-store: config-microservice.jks
    key-store-password: secret
    key-password: password
info:
  description: Config Server
  url: https://github.com/kbastani/spring-cloud-microservice-example
---
spring:
  application:
    name: configServer
  profiles:
    name: docker
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/kbastani/spring-boot-microservice-config
        health:
          repositories:
            movie:
              label: master
              profiles: cloud
            rating:
              label: master
              profiles: cloud
server:
  port: 8443
  ssl:
    key-store: config-microservice.jks
    key-store-password: secret
    key-password: password
info:
  description: Config Server
  url: https://github.com/kbastani/spring-cloud-microservice-example