spring:
  profiles:
    active: docker

---

spring:
  profiles: cloud
  jpa:
    show_sql: false
    database: MYSQL
    hibernate:
      ddl-auto: none
server:
  port: 9006
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-77.cfapps.io/eureka/
  instance:
    hostname: movie-77.cfapps.io
    nonSecurePort: 80
ribbon:
  eureka:
    enabled: true

---

spring:
  profiles: docker
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: hsqldb
server:
  port: 9006
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true

---

spring:
  profiles: scaleway
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: hsqldb
server:
  port: 9006
  address: 127.0.0.1
ribbon:
  eureka:
    enabled: false
eureka:
  waitTimeInMsWhenSyncEmpty: 0
  registration:
    enabled: false
  client:
    registerWithEureka: false
    fetchRegistry: false
